### ISSUE TITLE
License

### ISSUE THREAD

**Issue by spotlesscoder** [MacLemon/CongressChecklist#111]
Hi, could you please add a license for the resources provided in this repo? Maybe something like CC-BY-SA etc.? 

thank you :)

**Comment by MacLemon** [comment]
Good point, I completely forgot about putting a license on this list.
Now, putting one in after sooo many people have contributed, seems to be a legally complex task I'm afraid. (I guess I'd need a sign-off from every single person but I don't have an idea how that is supposed to work.)

Personally I'd totally be fine with [CC-BY](https://creativecommons.org/licenses/by/4.0/) but it feels wrong to be called the author of that work, when it's really a community effort that I just sparked.

Any suggestions on how to properly resolve this are more than welcome!

**Comment by johnjohndoe** [comment]
"public domain"

**Comment by spotlesscoder** [comment]
Yes, Public Domain sounds like a good idea
