### ISSUE TITLE
Link to DroidWall broken

### ISSUE THREAD

**Issue by LeSpocky** [MacLemon/CongressChecklist#68]
https://play.google.com/store/apps/details?id=com.googlecode.droidwall.free returns "not found"

**Comment by LeSpocky** [comment]
Is AFWall+ (Control network traffic) - https://f-droid.org/app/dev.ukanth.ufirewall an alternative one could link to?

**Comment by MacLemon** [comment]
Seems to make sense, can you send a pull request please?
