### ISSUE TITLE
Google Docs fights back (i.e. wants to delete file)

### ISSUE THREAD

**Issue by rugk** [MacLemon/CongressChecklist#78]
Probably it was not a good idea to host the USB-C matrix on Google docs: https://github.com/MacLemon/CongressChecklist/blame/master/README.md#L328

Because it tells me now them file is going to be deleted. Whatever that means… :thinking: 
https://screenshots.firefox.com/GOAoqQcI7DYyDhcJ/docs.google.com

Better to host somewhere else, next time… :smile: Maybe in a non-propriety and Google-controlled fashion. :wink:

**Comment by rugk** [comment]
![image](https://user-images.githubusercontent.com/11966684/50222922-08dc1a00-039a-11e9-8506-584e9e805252.png)

To translate:
> **The file will be deleted soon**
> This file is probably[!!??] going to be deleted soon. If you still want to access it, login to create a copy, download the file or ask the owner for access permission.
> [Login button]

Seriously, wtf. They don't even announce a deletion, they just want to force you into signing in. (The popup also only pops up a few seconds after everything loaded.)
If you hide that popup, everything is going fine.

And yes, if you hide that modal, you can download it, so here you go:
[USB-C Cables and Nexus Accessories.xlsx](https://github.com/MacLemon/CongressChecklist/files/2695023/USB-C.Cables.and.Nexus.Accessories.xlsx)
(.ods download obviously failed… :roll_eyes:)

Also, note that these are all Amazon referrer links, this note is well-hidden at the end.

**Comment by rugk** [comment]
Got an English screenshot:
![image](https://user-images.githubusercontent.com/11966684/50223688-3aee7b80-039c-11e9-83e5-dee766c9f241.png)

**Comment by rugk** [comment]
I don't get it. I mean if the author really deleted it – should not we have no access anymore to the file?
If I share a picture with you and delete it, I obviously don't want you being able to access it anymore?

That makes no sense…

**Comment by MacLemon** [comment]
The person who did this, is (or was) a Google employee. It's natural for them to use a Google Doc, maybe even a requirement. If the document goes away, we'll just remove the link. Over time the issue with bad USB-C cables will mostly fade anyway.
