### ISSUE TITLE
Updates for 36c3 (Emergency+More)

### ISSUE THREAD

**Issue by rwenz3l** [MacLemon/CongressChecklist#97]
In preparation for this year's congress we should update the checklist earlier than last time. If there are any changes necessary, we can collect them here and resolve them with a PR.

**Comment by Displayfreak** [comment]
Since the #Cccamp19 there is the new card10 badge, that would fit in „Gear“, „CCC originated Hardware“.

**Comment by MacLemon** [comment]
These things have been updated by now. (I'm aware, not really “in time” let alone “early”, but nonetheless…)
Thanks for the suggestions!
